### ISSUE TITLE
Golang 

### ISSUE THREAD

**Issue by gedw99** [peterstace/upgrade-go-module#3]
https://github.com/oligot/go-mod-upgrade helps ? 

It’s pretty study.

I js e a ton of mono repos that have hit repos inside. So am interested in the ability to upgrade them like this does .

it would be nice to replace the python with golang . We could walk the go path / src for git repos that have a go.mod in them and then do the rest of the flow ? 

I am a total newbies to python ..

I also use gh to automate things .

**Comment by peterstace** [comment]
Hi,

One of my explicit goals with this project was for it to help me learn Python (like you, I'm primarily a Go programmer). So, I don't have any interest in switching over to Go for this project.

Thanks for the suggestion, though!
